### ISSUE TITLE
Improve area selection in meta data tool

### ISSUE THREAD

**Issue by bstaton1** [bstaton1/KuskoHarvEst#210]
The way the areas are selected in the meta data tool is clumsy and could introduce errors by the user. This is because it is based on `textInput()`. Previously, this option only affected the text printed in the headers of the PDF reports, but I'm envisioning that this will be used to select which geographic strata to report as well now that there is interest in performing the flights over a larger area (see #177) or in some cases over a reduced area based on flight conditions.

It could be improved by:

- [x] Using `selectizeInput()` rather than `textInput()` -- this forces only accepted options to be selected
- [x] Only showing upstream boundary options that are actually upstream of the selected downstream boundary
- [x] Don't allow exiting until both downstream and upstream boundaries have been selected

**Comment by bstaton1** [comment]
Closed by #211
