### ISSUE TITLE
Remove Need to Enter Spatial Coverage In Meta Data Tool

### ISSUE THREAD

**Issue by bstaton1** [bstaton1/KuskoHarvEst#216]
The user currently must accept the defaults/hand enter the spatial coverage of the estimate in the meta data tool. This may create confusion in the future, and it is only ever used to print the range at the top of the estimate document -- it doesn't get used to select the data or perform subsetting. It is thus unnecessary (can automate this) and can be discarded.

The solution will be to:

- [x] Create a `get_flight_strata()` function that extracts/returns the names of the strata found in the processed flight data set.
  - [x] Should return informative error if a stratum is found in flight data that is not accepted
- [x] Implement this in `build_yaml()` -- replace `meta$ds_bound`/`meta$us_bound` with a call to `get_flight_strata()`
- [x] Delete the strata boundaries widgets from the meta data tool

**Comment by bstaton1** [comment]
Closed by #217
