### ISSUE TITLE
Running Idea/To-Do Board

### ISSUE THREAD

**Issue by bstaton1** [bstaton1/KuskoHarvEst#3]
# Idea/To-Do Board

> This will serve as a place to store ideas and tasks that are in a less developed stage than a full issue. Generally, a topic will be moved to a complete issue before work begins on it. When the topic is addressed, it will be checked off and the pull request that addresses it will be referenced. Generally this issue won't be referenced in other issues or in pull requests.

## Estimation Code

- [x] Improve interview data preparation code (I #8 / PR #10)
- [x] Improve flight data preparation code (I #11 / PR #12)
- [x] Improve effort estimation code (PR #14)
- [x] Improve harvest estimation code (I #15 / PR #16)
- [x] Improve randomization code (I #17 / PR #18) 
- [x] Build a function to apportion effort to strata (I #19 / PR #24) 
- [x] Delete catch rate data from the `prepare_interviews()` function, these are generated in `estimate_harvest()` (I #21 / PR #22)
- [x] Build a function to estimate harvest for all strata (wrapper around `estimate_harvest()`) (I #28 / PR #32)
- [x] Build a function to automate the bootstrap for a given year (I #30 / PR #32) 
- [x] Improve bootstrap summarization code (I #31 / PR #33)
- [x] Build a framework for automated checking of suitability for interview usage in different tasks (I #26 / PR #40) 
- [x] Build a function to determine pooling of interviews when some strata have few (I #27 / PR #39)
- [x] Ensure trips available functionality is working consistently with the old method (I #37 / PR #38)
- [x] Build automated correction for impossible soak times (I #42 / PR #45)
- [ ] Build leave-one-out quality assurance check (I #41)
- [x] Integrate suitability checks into other functions (I #43 / PR #45)  
- [ ] In interview data files, add columns for trip start date and trip end date
- [ ] Somehow handle two dates at a time -- without forcing all function to accept a date argument. Maybe this can be handled through the dropdown menu. Perhaps just do everything multiple times if the option "Opener Spanned Multiple Days?" is selected?
- [x] Follow up with Bill and Gary about things that warrant questioning an interview
- [ ] Run data from other openers through program to see if any failures occur

* Create a function to show an example input file for each data type
* Develop candidate rules for discarding records deemed unreliable - _bring to group for feedback_
* Consider using a cluster to speed up bootstrapping calculations?

## Reporting Code

* Break main sections into child `.Rmd` files
* Create a nice `preamble.tex` that applies to all PDF files - consistent styling
* Figure out a way to have minimal YAML header editing

## Interface/workflow Code

* Create RStudio project template
* Experiment with creating an RStudio Add-in
